apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.contaServico.nome }}
  labels:
    {{- include "orquestrapay.rotulos" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.contaServico.funcaoIamArn | quote }}
    argocd.argoproj.io/sync-wave: "-11"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.contaServico.semAwsNome }}
  labels:
    {{- include "orquestrapay.rotulos" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.contaServico.segredosNome }}
  labels:
    {{- include "orquestrapay.rotulos" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.contaServico.segredosFuncaoIamArn | quote }}
    argocd.argoproj.io/sync-wave: "-11"
automountServiceAccountToken: false
